s="ACGAGATCCCGTGGTCCGGCGCTTCCGTCTTCGTGTCGATCGGGTAGAATAATGTGCGCATCACAGTGTATGGCTAGAGACATTCGATGTCGTCAGCTGCGTCCAACCGCAAATGAGGTGTTTTCATATCTAAAGTGATGCTTAAGGCCAGTGCGTCATTTCTGTGTGCTTTACTCCAGTCTCCTGGCATGCGGCGGAGGCTTTTCGTCCAACCCGGTATATGGCGTTTTTAAAAGGCGATGGGAAAAGCATGAACGTGAACCCTGTGCTGGTACTCAGGGTGACACATTTAATCAACCCCAGTTTCGAAGGTTAACGGAATGGGCCGCCGGAGCATAATTACCTCCTTACAAATAACTCTTAGACCGTCCTTGCTTCGCAAGACGCCCAATGGGCATATCCAACCATCCGTACCCCCGGAAAACGTATTTGGCCAAGGACCAATAACGTTATCGAGCCACCTCGGCCTAACCCTGGCACTACGCAACACACACTAACTGAGGGTAATTCAGTACCAAGAGCCGGAGCCCAATCGTTGTGCATGGACTAAACCTAATTGGATAGACAGTATGCGAGGTCGATGGCCGACCCGCCACTACACATACCTTCTCCATAGGGAAGGCTATTCGCACAGATTTCCACACCGCAATGGAGTTAGTAGCGATCTTAAATGGCGCTTCTACCGTGGCCGCTCTACTCTTTCAAACACACAGACTCGGGCACGCTCACCTCGCCGGCTAGTCATACCCGTAGTGCAATCAGGGCTGTGTATGCAAAAACTCAATTCGATAGCTTCTGCCGGATCAAACCAGAGATTACACGCCTCCGATGCTCCGTTTTATTTATTCATCGATTGGTTATACGGTCATGCTGTACGTCTGCGCGACTATTTGTGGGTCGTTAT"

rev = s[::-1]
modList=""
for letter in rev:
	  if letter == "A":
	  	 modList += 'T'
	  elif letter == "C":
	  	   modList += "G"
	  elif letter == "G":
	  	    modList += "C"
	  elif letter == "T":
	  	   modList += "A"
	  	   
print(modList)


